import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Travel Site Admin",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <div className="w-full max-w-[1020px] m-auto p-4">
          <nav className="w-full h-16 flex items-center justify-between mb-4">
            <div className="text-2xl font-bold">Travel Site Admin</div>
            <div>
              <a href="/destinations" className="mr-4 text-blue-500 hover:underline">
                Destinations
              </a>
              <a href="/destinations/new" className="text-blue-500 hover:underline">
                Add Destination
              </a>
            </div>
          </nav>  
          {children}
        </div>
      </body>
    </html>
  );
}
